#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Project_Data")]
	public partial class BaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertCandidat(Candidat instance);
    partial void UpdateCandidat(Candidat instance);
    partial void DeleteCandidat(Candidat instance);
    partial void InsertConges(Conges instance);
    partial void UpdateConges(Conges instance);
    partial void DeleteConges(Conges instance);
    partial void InsertEmploye(Employe instance);
    partial void UpdateEmploye(Employe instance);
    partial void DeleteEmploye(Employe instance);
    partial void InsertEntretient(Entretient instance);
    partial void UpdateEntretient(Entretient instance);
    partial void DeleteEntretient(Entretient instance);
    partial void InsertEvaluation(Evaluation instance);
    partial void UpdateEvaluation(Evaluation instance);
    partial void DeleteEvaluation(Evaluation instance);
    partial void InsertParametres(Parametres instance);
    partial void UpdateParametres(Parametres instance);
    partial void DeleteParametres(Parametres instance);
    partial void InsertSalaires(Salaires instance);
    partial void UpdateSalaires(Salaires instance);
    partial void DeleteSalaires(Salaires instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    #endregion
		
		public BaseDataContext() : 
				base(global::WpfApplication2.Properties.Settings.Default.Project_DataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Candidat> Candidat
		{
			get
			{
				return this.GetTable<Candidat>();
			}
		}
		
		public System.Data.Linq.Table<Conges> Conges
		{
			get
			{
				return this.GetTable<Conges>();
			}
		}
		
		public System.Data.Linq.Table<Employe> Employe
		{
			get
			{
				return this.GetTable<Employe>();
			}
		}
		
		public System.Data.Linq.Table<Entretient> Entretient
		{
			get
			{
				return this.GetTable<Entretient>();
			}
		}
		
		public System.Data.Linq.Table<Evaluation> Evaluation
		{
			get
			{
				return this.GetTable<Evaluation>();
			}
		}
		
		public System.Data.Linq.Table<Parametres> Parametres
		{
			get
			{
				return this.GetTable<Parametres>();
			}
		}
		
		public System.Data.Linq.Table<Salaires> Salaires
		{
			get
			{
				return this.GetTable<Salaires>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Candidat")]
	public partial class Candidat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NumeroCandidat;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _NumeroTel;
		
		private string _IntitulePoste;
		
		private System.Data.Linq.Binary _cvCabdidat;
		
		private EntitySet<Entretient> _Entretient;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumeroCandidatChanging(int value);
    partial void OnNumeroCandidatChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnNumeroTelChanging(string value);
    partial void OnNumeroTelChanged();
    partial void OnIntitulePosteChanging(string value);
    partial void OnIntitulePosteChanged();
    partial void OncvCabdidatChanging(System.Data.Linq.Binary value);
    partial void OncvCabdidatChanged();
    #endregion
		
		public Candidat()
		{
			this._Entretient = new EntitySet<Entretient>(new Action<Entretient>(this.attach_Entretient), new Action<Entretient>(this.detach_Entretient));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCandidat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NumeroCandidat
		{
			get
			{
				return this._NumeroCandidat;
			}
			set
			{
				if ((this._NumeroCandidat != value))
				{
					this.OnNumeroCandidatChanging(value);
					this.SendPropertyChanging();
					this._NumeroCandidat = value;
					this.SendPropertyChanged("NumeroCandidat");
					this.OnNumeroCandidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(20)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(20)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTel", DbType="NVarChar(20)")]
		public string NumeroTel
		{
			get
			{
				return this._NumeroTel;
			}
			set
			{
				if ((this._NumeroTel != value))
				{
					this.OnNumeroTelChanging(value);
					this.SendPropertyChanging();
					this._NumeroTel = value;
					this.SendPropertyChanged("NumeroTel");
					this.OnNumeroTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntitulePoste", DbType="NVarChar(50)")]
		public string IntitulePoste
		{
			get
			{
				return this._IntitulePoste;
			}
			set
			{
				if ((this._IntitulePoste != value))
				{
					this.OnIntitulePosteChanging(value);
					this.SendPropertyChanging();
					this._IntitulePoste = value;
					this.SendPropertyChanged("IntitulePoste");
					this.OnIntitulePosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvCabdidat", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary cvCabdidat
		{
			get
			{
				return this._cvCabdidat;
			}
			set
			{
				if ((this._cvCabdidat != value))
				{
					this.OncvCabdidatChanging(value);
					this.SendPropertyChanging();
					this._cvCabdidat = value;
					this.SendPropertyChanged("cvCabdidat");
					this.OncvCabdidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Candidat_Entretient", Storage="_Entretient", ThisKey="NumeroCandidat", OtherKey="NumeroCandidat")]
		public EntitySet<Entretient> Entretient
		{
			get
			{
				return this._Entretient;
			}
			set
			{
				this._Entretient.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Entretient(Entretient entity)
		{
			this.SendPropertyChanging();
			entity.Candidat = this;
		}
		
		private void detach_Entretient(Entretient entity)
		{
			this.SendPropertyChanging();
			entity.Candidat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Conges")]
	public partial class Conges : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Matricule;
		
		private System.DateTime _DateDebut;
		
		private System.DateTime _DateFin;
		
		private string _Type;
		
		private System.Data.Linq.Binary _Formulaire;
		
		private System.DateTime _DateRetour;
		
		private EntityRef<Employe> _Employe;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMatriculeChanging(System.Nullable<int> value);
    partial void OnMatriculeChanged();
    partial void OnDateDebutChanging(System.DateTime value);
    partial void OnDateDebutChanged();
    partial void OnDateFinChanging(System.DateTime value);
    partial void OnDateFinChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnFormulaireChanging(System.Data.Linq.Binary value);
    partial void OnFormulaireChanged();
    partial void OnDateRetourChanging(System.DateTime value);
    partial void OnDateRetourChanged();
    #endregion
		
		public Conges()
		{
			this._Employe = default(EntityRef<Employe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricule", DbType="Int")]
		public System.Nullable<int> Matricule
		{
			get
			{
				return this._Matricule;
			}
			set
			{
				if ((this._Matricule != value))
				{
					if (this._Employe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatriculeChanging(value);
					this.SendPropertyChanging();
					this._Matricule = value;
					this.SendPropertyChanged("Matricule");
					this.OnMatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDebut", DbType="Date NOT NULL")]
		public System.DateTime DateDebut
		{
			get
			{
				return this._DateDebut;
			}
			set
			{
				if ((this._DateDebut != value))
				{
					this.OnDateDebutChanging(value);
					this.SendPropertyChanging();
					this._DateDebut = value;
					this.SendPropertyChanged("DateDebut");
					this.OnDateDebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFin", DbType="Date NOT NULL")]
		public System.DateTime DateFin
		{
			get
			{
				return this._DateFin;
			}
			set
			{
				if ((this._DateFin != value))
				{
					this.OnDateFinChanging(value);
					this.SendPropertyChanging();
					this._DateFin = value;
					this.SendPropertyChanged("DateFin");
					this.OnDateFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Formulaire", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Formulaire
		{
			get
			{
				return this._Formulaire;
			}
			set
			{
				if ((this._Formulaire != value))
				{
					this.OnFormulaireChanging(value);
					this.SendPropertyChanging();
					this._Formulaire = value;
					this.SendPropertyChanged("Formulaire");
					this.OnFormulaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRetour", DbType="Date NOT NULL")]
		public System.DateTime DateRetour
		{
			get
			{
				return this._DateRetour;
			}
			set
			{
				if ((this._DateRetour != value))
				{
					this.OnDateRetourChanging(value);
					this.SendPropertyChanging();
					this._DateRetour = value;
					this.SendPropertyChanged("DateRetour");
					this.OnDateRetourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_Conges", Storage="_Employe", ThisKey="Matricule", OtherKey="Matricule", IsForeignKey=true)]
		public Employe Employe
		{
			get
			{
				return this._Employe.Entity;
			}
			set
			{
				Employe previousValue = this._Employe.Entity;
				if (((previousValue != value) 
							|| (this._Employe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employe.Entity = null;
						previousValue.Conges.Remove(this);
					}
					this._Employe.Entity = value;
					if ((value != null))
					{
						value.Conges.Add(this);
						this._Matricule = value.Matricule;
					}
					else
					{
						this._Matricule = default(Nullable<int>);
					}
					this.SendPropertyChanged("Employe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employe")]
	public partial class Employe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Matricule;
		
		private string _Nom;
		
		private string _Prenom;
		
		private System.Nullable<System.DateTime> _DateDeNaissance;
		
		private string _SituationFamille;
		
		private System.Nullable<System.DateTime> _DateEmbauche;
		
		private string _Poste;
		
		private string _Responsable;
		
		private string _Projet;
		
		private string _NumImatSocial;
		
		private System.Data.Linq.Binary _CV;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _DateDeDemission;
		
		private string _Adresse;
		
		private string _NumeroTel;
		
		private string _Email;
		
		private System.Nullable<double> _NbJourConge;
		
		private string _CoorBancaires;
		
		private string _Commentaires;
		
		private string _Sexe;
		
		private string _Wilaya;
		
		private System.Nullable<int> _CongesConsomme;
		
		private System.Data.Linq.Binary _ContratTravail;
		
		private System.Data.Linq.Binary _PhotoProfil;
		
		private EntitySet<Conges> _Conges;
		
		private EntitySet<Evaluation> _Evaluation;
		
		private EntitySet<Salaires> _Salaires;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatriculeChanging(int value);
    partial void OnMatriculeChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnDateDeNaissanceChanging(System.Nullable<System.DateTime> value);
    partial void OnDateDeNaissanceChanged();
    partial void OnSituationFamilleChanging(string value);
    partial void OnSituationFamilleChanged();
    partial void OnDateEmbaucheChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEmbaucheChanged();
    partial void OnPosteChanging(string value);
    partial void OnPosteChanged();
    partial void OnResponsableChanging(string value);
    partial void OnResponsableChanged();
    partial void OnProjetChanging(string value);
    partial void OnProjetChanged();
    partial void OnNumImatSocialChanging(string value);
    partial void OnNumImatSocialChanged();
    partial void OnCVChanging(System.Data.Linq.Binary value);
    partial void OnCVChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnDateDeDemissionChanging(System.Nullable<System.DateTime> value);
    partial void OnDateDeDemissionChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnNumeroTelChanging(string value);
    partial void OnNumeroTelChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNbJourCongeChanging(System.Nullable<double> value);
    partial void OnNbJourCongeChanged();
    partial void OnCoorBancairesChanging(string value);
    partial void OnCoorBancairesChanged();
    partial void OnCommentairesChanging(string value);
    partial void OnCommentairesChanged();
    partial void OnSexeChanging(string value);
    partial void OnSexeChanged();
    partial void OnWilayaChanging(string value);
    partial void OnWilayaChanged();
    partial void OnCongesConsommeChanging(System.Nullable<int> value);
    partial void OnCongesConsommeChanged();
    partial void OnContratTravailChanging(System.Data.Linq.Binary value);
    partial void OnContratTravailChanged();
    partial void OnPhotoProfilChanging(System.Data.Linq.Binary value);
    partial void OnPhotoProfilChanged();
    #endregion
		
		public Employe()
		{
			this._Conges = new EntitySet<Conges>(new Action<Conges>(this.attach_Conges), new Action<Conges>(this.detach_Conges));
			this._Evaluation = new EntitySet<Evaluation>(new Action<Evaluation>(this.attach_Evaluation), new Action<Evaluation>(this.detach_Evaluation));
			this._Salaires = new EntitySet<Salaires>(new Action<Salaires>(this.attach_Salaires), new Action<Salaires>(this.detach_Salaires));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricule", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Matricule
		{
			get
			{
				return this._Matricule;
			}
			set
			{
				if ((this._Matricule != value))
				{
					this.OnMatriculeChanging(value);
					this.SendPropertyChanging();
					this._Matricule = value;
					this.SendPropertyChanged("Matricule");
					this.OnMatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDeNaissance", DbType="Date")]
		public System.Nullable<System.DateTime> DateDeNaissance
		{
			get
			{
				return this._DateDeNaissance;
			}
			set
			{
				if ((this._DateDeNaissance != value))
				{
					this.OnDateDeNaissanceChanging(value);
					this.SendPropertyChanging();
					this._DateDeNaissance = value;
					this.SendPropertyChanged("DateDeNaissance");
					this.OnDateDeNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SituationFamille", DbType="NVarChar(20)")]
		public string SituationFamille
		{
			get
			{
				return this._SituationFamille;
			}
			set
			{
				if ((this._SituationFamille != value))
				{
					this.OnSituationFamilleChanging(value);
					this.SendPropertyChanging();
					this._SituationFamille = value;
					this.SendPropertyChanged("SituationFamille");
					this.OnSituationFamilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEmbauche", DbType="Date")]
		public System.Nullable<System.DateTime> DateEmbauche
		{
			get
			{
				return this._DateEmbauche;
			}
			set
			{
				if ((this._DateEmbauche != value))
				{
					this.OnDateEmbaucheChanging(value);
					this.SendPropertyChanging();
					this._DateEmbauche = value;
					this.SendPropertyChanged("DateEmbauche");
					this.OnDateEmbaucheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poste", DbType="NVarChar(80)")]
		public string Poste
		{
			get
			{
				return this._Poste;
			}
			set
			{
				if ((this._Poste != value))
				{
					this.OnPosteChanging(value);
					this.SendPropertyChanging();
					this._Poste = value;
					this.SendPropertyChanged("Poste");
					this.OnPosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsable", DbType="NVarChar(50)")]
		public string Responsable
		{
			get
			{
				return this._Responsable;
			}
			set
			{
				if ((this._Responsable != value))
				{
					this.OnResponsableChanging(value);
					this.SendPropertyChanging();
					this._Responsable = value;
					this.SendPropertyChanged("Responsable");
					this.OnResponsableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Projet", DbType="NVarChar(100)")]
		public string Projet
		{
			get
			{
				return this._Projet;
			}
			set
			{
				if ((this._Projet != value))
				{
					this.OnProjetChanging(value);
					this.SendPropertyChanging();
					this._Projet = value;
					this.SendPropertyChanged("Projet");
					this.OnProjetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumImatSocial", DbType="NVarChar(100)")]
		public string NumImatSocial
		{
			get
			{
				return this._NumImatSocial;
			}
			set
			{
				if ((this._NumImatSocial != value))
				{
					this.OnNumImatSocialChanging(value);
					this.SendPropertyChanging();
					this._NumImatSocial = value;
					this.SendPropertyChanged("NumImatSocial");
					this.OnNumImatSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CV", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CV
		{
			get
			{
				return this._CV;
			}
			set
			{
				if ((this._CV != value))
				{
					this.OnCVChanging(value);
					this.SendPropertyChanging();
					this._CV = value;
					this.SendPropertyChanged("CV");
					this.OnCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDeDemission", DbType="Date")]
		public System.Nullable<System.DateTime> DateDeDemission
		{
			get
			{
				return this._DateDeDemission;
			}
			set
			{
				if ((this._DateDeDemission != value))
				{
					this.OnDateDeDemissionChanging(value);
					this.SendPropertyChanging();
					this._DateDeDemission = value;
					this.SendPropertyChanged("DateDeDemission");
					this.OnDateDeDemissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTel", DbType="NVarChar(20)")]
		public string NumeroTel
		{
			get
			{
				return this._NumeroTel;
			}
			set
			{
				if ((this._NumeroTel != value))
				{
					this.OnNumeroTelChanging(value);
					this.SendPropertyChanging();
					this._NumeroTel = value;
					this.SendPropertyChanged("NumeroTel");
					this.OnNumeroTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NbJourConge", DbType="Float")]
		public System.Nullable<double> NbJourConge
		{
			get
			{
				return this._NbJourConge;
			}
			set
			{
				if ((this._NbJourConge != value))
				{
					this.OnNbJourCongeChanging(value);
					this.SendPropertyChanging();
					this._NbJourConge = value;
					this.SendPropertyChanged("NbJourConge");
					this.OnNbJourCongeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoorBancaires", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string CoorBancaires
		{
			get
			{
				return this._CoorBancaires;
			}
			set
			{
				if ((this._CoorBancaires != value))
				{
					this.OnCoorBancairesChanging(value);
					this.SendPropertyChanging();
					this._CoorBancaires = value;
					this.SendPropertyChanged("CoorBancaires");
					this.OnCoorBancairesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commentaires", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Commentaires
		{
			get
			{
				return this._Commentaires;
			}
			set
			{
				if ((this._Commentaires != value))
				{
					this.OnCommentairesChanging(value);
					this.SendPropertyChanging();
					this._Commentaires = value;
					this.SendPropertyChanged("Commentaires");
					this.OnCommentairesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="NVarChar(15)")]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wilaya", DbType="NVarChar(50)")]
		public string Wilaya
		{
			get
			{
				return this._Wilaya;
			}
			set
			{
				if ((this._Wilaya != value))
				{
					this.OnWilayaChanging(value);
					this.SendPropertyChanging();
					this._Wilaya = value;
					this.SendPropertyChanged("Wilaya");
					this.OnWilayaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongesConsomme", DbType="Int")]
		public System.Nullable<int> CongesConsomme
		{
			get
			{
				return this._CongesConsomme;
			}
			set
			{
				if ((this._CongesConsomme != value))
				{
					this.OnCongesConsommeChanging(value);
					this.SendPropertyChanging();
					this._CongesConsomme = value;
					this.SendPropertyChanged("CongesConsomme");
					this.OnCongesConsommeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContratTravail", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ContratTravail
		{
			get
			{
				return this._ContratTravail;
			}
			set
			{
				if ((this._ContratTravail != value))
				{
					this.OnContratTravailChanging(value);
					this.SendPropertyChanging();
					this._ContratTravail = value;
					this.SendPropertyChanged("ContratTravail");
					this.OnContratTravailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoProfil", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PhotoProfil
		{
			get
			{
				return this._PhotoProfil;
			}
			set
			{
				if ((this._PhotoProfil != value))
				{
					this.OnPhotoProfilChanging(value);
					this.SendPropertyChanging();
					this._PhotoProfil = value;
					this.SendPropertyChanged("PhotoProfil");
					this.OnPhotoProfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_Conges", Storage="_Conges", ThisKey="Matricule", OtherKey="Matricule")]
		public EntitySet<Conges> Conges
		{
			get
			{
				return this._Conges;
			}
			set
			{
				this._Conges.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_Evaluation", Storage="_Evaluation", ThisKey="Matricule", OtherKey="Matricule")]
		public EntitySet<Evaluation> Evaluation
		{
			get
			{
				return this._Evaluation;
			}
			set
			{
				this._Evaluation.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_Salaires", Storage="_Salaires", ThisKey="Matricule", OtherKey="Matricule")]
		public EntitySet<Salaires> Salaires
		{
			get
			{
				return this._Salaires;
			}
			set
			{
				this._Salaires.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Conges(Conges entity)
		{
			this.SendPropertyChanging();
			entity.Employe = this;
		}
		
		private void detach_Conges(Conges entity)
		{
			this.SendPropertyChanging();
			entity.Employe = null;
		}
		
		private void attach_Evaluation(Evaluation entity)
		{
			this.SendPropertyChanging();
			entity.Employe = this;
		}
		
		private void detach_Evaluation(Evaluation entity)
		{
			this.SendPropertyChanging();
			entity.Employe = null;
		}
		
		private void attach_Salaires(Salaires entity)
		{
			this.SendPropertyChanging();
			entity.Employe = this;
		}
		
		private void detach_Salaires(Salaires entity)
		{
			this.SendPropertyChanging();
			entity.Employe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entretient")]
	public partial class Entretient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NumEntret;
		
		private string _Experience;
		
		private string _Question1;
		
		private string _EvaluationQuestion1;
		
		private string _Question2;
		
		private string _EvaluationQuestion2;
		
		private System.Nullable<decimal> _SalaireDesire;
		
		private string _Status;
		
		private string _Commentaires;
		
		private string _EtapeSuivante;
		
		private System.Nullable<int> _NumeroCandidat;
		
		private System.Nullable<System.DateTime> _DateEntretien;
		
		private int _fait;
		
		private EntityRef<Candidat> _Candidat;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumEntretChanging(int value);
    partial void OnNumEntretChanged();
    partial void OnExperienceChanging(string value);
    partial void OnExperienceChanged();
    partial void OnQuestion1Changing(string value);
    partial void OnQuestion1Changed();
    partial void OnEvaluationQuestion1Changing(string value);
    partial void OnEvaluationQuestion1Changed();
    partial void OnQuestion2Changing(string value);
    partial void OnQuestion2Changed();
    partial void OnEvaluationQuestion2Changing(string value);
    partial void OnEvaluationQuestion2Changed();
    partial void OnSalaireDesireChanging(System.Nullable<decimal> value);
    partial void OnSalaireDesireChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCommentairesChanging(string value);
    partial void OnCommentairesChanged();
    partial void OnEtapeSuivanteChanging(string value);
    partial void OnEtapeSuivanteChanged();
    partial void OnNumeroCandidatChanging(System.Nullable<int> value);
    partial void OnNumeroCandidatChanged();
    partial void OnDateEntretienChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEntretienChanged();
    partial void OnfaitChanging(int value);
    partial void OnfaitChanged();
    #endregion
		
		public Entretient()
		{
			this._Candidat = default(EntityRef<Candidat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumEntret", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NumEntret
		{
			get
			{
				return this._NumEntret;
			}
			set
			{
				if ((this._NumEntret != value))
				{
					this.OnNumEntretChanging(value);
					this.SendPropertyChanging();
					this._NumEntret = value;
					this.SendPropertyChanged("NumEntret");
					this.OnNumEntretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience", DbType="NVarChar(50)")]
		public string Experience
		{
			get
			{
				return this._Experience;
			}
			set
			{
				if ((this._Experience != value))
				{
					this.OnExperienceChanging(value);
					this.SendPropertyChanging();
					this._Experience = value;
					this.SendPropertyChanged("Experience");
					this.OnExperienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question1", DbType="NVarChar(50)")]
		public string Question1
		{
			get
			{
				return this._Question1;
			}
			set
			{
				if ((this._Question1 != value))
				{
					this.OnQuestion1Changing(value);
					this.SendPropertyChanging();
					this._Question1 = value;
					this.SendPropertyChanged("Question1");
					this.OnQuestion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvaluationQuestion1", DbType="NVarChar(50)")]
		public string EvaluationQuestion1
		{
			get
			{
				return this._EvaluationQuestion1;
			}
			set
			{
				if ((this._EvaluationQuestion1 != value))
				{
					this.OnEvaluationQuestion1Changing(value);
					this.SendPropertyChanging();
					this._EvaluationQuestion1 = value;
					this.SendPropertyChanged("EvaluationQuestion1");
					this.OnEvaluationQuestion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question2", DbType="NVarChar(50)")]
		public string Question2
		{
			get
			{
				return this._Question2;
			}
			set
			{
				if ((this._Question2 != value))
				{
					this.OnQuestion2Changing(value);
					this.SendPropertyChanging();
					this._Question2 = value;
					this.SendPropertyChanged("Question2");
					this.OnQuestion2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvaluationQuestion2", DbType="NVarChar(50)")]
		public string EvaluationQuestion2
		{
			get
			{
				return this._EvaluationQuestion2;
			}
			set
			{
				if ((this._EvaluationQuestion2 != value))
				{
					this.OnEvaluationQuestion2Changing(value);
					this.SendPropertyChanging();
					this._EvaluationQuestion2 = value;
					this.SendPropertyChanged("EvaluationQuestion2");
					this.OnEvaluationQuestion2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaireDesire", DbType="Money")]
		public System.Nullable<decimal> SalaireDesire
		{
			get
			{
				return this._SalaireDesire;
			}
			set
			{
				if ((this._SalaireDesire != value))
				{
					this.OnSalaireDesireChanging(value);
					this.SendPropertyChanging();
					this._SalaireDesire = value;
					this.SendPropertyChanged("SalaireDesire");
					this.OnSalaireDesireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commentaires", DbType="NVarChar(100)")]
		public string Commentaires
		{
			get
			{
				return this._Commentaires;
			}
			set
			{
				if ((this._Commentaires != value))
				{
					this.OnCommentairesChanging(value);
					this.SendPropertyChanging();
					this._Commentaires = value;
					this.SendPropertyChanged("Commentaires");
					this.OnCommentairesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EtapeSuivante", DbType="NVarChar(50)")]
		public string EtapeSuivante
		{
			get
			{
				return this._EtapeSuivante;
			}
			set
			{
				if ((this._EtapeSuivante != value))
				{
					this.OnEtapeSuivanteChanging(value);
					this.SendPropertyChanging();
					this._EtapeSuivante = value;
					this.SendPropertyChanged("EtapeSuivante");
					this.OnEtapeSuivanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCandidat", DbType="Int")]
		public System.Nullable<int> NumeroCandidat
		{
			get
			{
				return this._NumeroCandidat;
			}
			set
			{
				if ((this._NumeroCandidat != value))
				{
					if (this._Candidat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNumeroCandidatChanging(value);
					this.SendPropertyChanging();
					this._NumeroCandidat = value;
					this.SendPropertyChanged("NumeroCandidat");
					this.OnNumeroCandidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEntretien", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEntretien
		{
			get
			{
				return this._DateEntretien;
			}
			set
			{
				if ((this._DateEntretien != value))
				{
					this.OnDateEntretienChanging(value);
					this.SendPropertyChanging();
					this._DateEntretien = value;
					this.SendPropertyChanged("DateEntretien");
					this.OnDateEntretienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fait", DbType="Int NOT NULL")]
		public int fait
		{
			get
			{
				return this._fait;
			}
			set
			{
				if ((this._fait != value))
				{
					this.OnfaitChanging(value);
					this.SendPropertyChanging();
					this._fait = value;
					this.SendPropertyChanged("fait");
					this.OnfaitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Candidat_Entretient", Storage="_Candidat", ThisKey="NumeroCandidat", OtherKey="NumeroCandidat", IsForeignKey=true)]
		public Candidat Candidat
		{
			get
			{
				return this._Candidat.Entity;
			}
			set
			{
				Candidat previousValue = this._Candidat.Entity;
				if (((previousValue != value) 
							|| (this._Candidat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Candidat.Entity = null;
						previousValue.Entretient.Remove(this);
					}
					this._Candidat.Entity = value;
					if ((value != null))
					{
						value.Entretient.Add(this);
						this._NumeroCandidat = value.NumeroCandidat;
					}
					else
					{
						this._NumeroCandidat = default(Nullable<int>);
					}
					this.SendPropertyChanged("Candidat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Evaluation")]
	public partial class Evaluation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Matricule;
		
		private System.Nullable<System.DateTime> _DateEval;
		
		private System.Data.Linq.Binary _FichierEval;
		
		private System.Nullable<decimal> _NoteEval;
		
		private EntityRef<Employe> _Employe;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMatriculeChanging(System.Nullable<int> value);
    partial void OnMatriculeChanged();
    partial void OnDateEvalChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEvalChanged();
    partial void OnFichierEvalChanging(System.Data.Linq.Binary value);
    partial void OnFichierEvalChanged();
    partial void OnNoteEvalChanging(System.Nullable<decimal> value);
    partial void OnNoteEvalChanged();
    #endregion
		
		public Evaluation()
		{
			this._Employe = default(EntityRef<Employe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricule", DbType="Int")]
		public System.Nullable<int> Matricule
		{
			get
			{
				return this._Matricule;
			}
			set
			{
				if ((this._Matricule != value))
				{
					if (this._Employe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatriculeChanging(value);
					this.SendPropertyChanging();
					this._Matricule = value;
					this.SendPropertyChanged("Matricule");
					this.OnMatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEval", DbType="Date")]
		public System.Nullable<System.DateTime> DateEval
		{
			get
			{
				return this._DateEval;
			}
			set
			{
				if ((this._DateEval != value))
				{
					this.OnDateEvalChanging(value);
					this.SendPropertyChanging();
					this._DateEval = value;
					this.SendPropertyChanged("DateEval");
					this.OnDateEvalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FichierEval", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FichierEval
		{
			get
			{
				return this._FichierEval;
			}
			set
			{
				if ((this._FichierEval != value))
				{
					this.OnFichierEvalChanging(value);
					this.SendPropertyChanging();
					this._FichierEval = value;
					this.SendPropertyChanged("FichierEval");
					this.OnFichierEvalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteEval", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> NoteEval
		{
			get
			{
				return this._NoteEval;
			}
			set
			{
				if ((this._NoteEval != value))
				{
					this.OnNoteEvalChanging(value);
					this.SendPropertyChanging();
					this._NoteEval = value;
					this.SendPropertyChanged("NoteEval");
					this.OnNoteEvalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_Evaluation", Storage="_Employe", ThisKey="Matricule", OtherKey="Matricule", IsForeignKey=true)]
		public Employe Employe
		{
			get
			{
				return this._Employe.Entity;
			}
			set
			{
				Employe previousValue = this._Employe.Entity;
				if (((previousValue != value) 
							|| (this._Employe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employe.Entity = null;
						previousValue.Evaluation.Remove(this);
					}
					this._Employe.Entity = value;
					if ((value != null))
					{
						value.Evaluation.Add(this);
						this._Matricule = value.Matricule;
					}
					else
					{
						this._Matricule = default(Nullable<int>);
					}
					this.SendPropertyChanged("Employe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parametres")]
	public partial class Parametres : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Raison_Sociale;
		
		private string _Speciaite;
		
		private string _Site_Web;
		
		private string _NomGerant;
		
		private string _PrenomGerant;
		
		private string _Adresse;
		
		private string _Telephone;
		
		private string _Fax;
		
		private string _MailGerant;
		
		private string _NumeroRC;
		
		private string _IdFiscale;
		
		private System.Data.Linq.Binary _Logo;
		
		private string _Wilaya;
		
		private int _Cle;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRaison_SocialeChanging(string value);
    partial void OnRaison_SocialeChanged();
    partial void OnSpeciaiteChanging(string value);
    partial void OnSpeciaiteChanged();
    partial void OnSite_WebChanging(string value);
    partial void OnSite_WebChanged();
    partial void OnNomGerantChanging(string value);
    partial void OnNomGerantChanged();
    partial void OnPrenomGerantChanging(string value);
    partial void OnPrenomGerantChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnMailGerantChanging(string value);
    partial void OnMailGerantChanged();
    partial void OnNumeroRCChanging(string value);
    partial void OnNumeroRCChanged();
    partial void OnIdFiscaleChanging(string value);
    partial void OnIdFiscaleChanged();
    partial void OnLogoChanging(System.Data.Linq.Binary value);
    partial void OnLogoChanged();
    partial void OnWilayaChanging(string value);
    partial void OnWilayaChanged();
    partial void OnCleChanging(int value);
    partial void OnCleChanged();
    #endregion
		
		public Parametres()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Raison Sociale]", Storage="_Raison_Sociale", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Raison_Sociale
		{
			get
			{
				return this._Raison_Sociale;
			}
			set
			{
				if ((this._Raison_Sociale != value))
				{
					this.OnRaison_SocialeChanging(value);
					this.SendPropertyChanging();
					this._Raison_Sociale = value;
					this.SendPropertyChanged("Raison_Sociale");
					this.OnRaison_SocialeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speciaite", DbType="NVarChar(MAX)")]
		public string Speciaite
		{
			get
			{
				return this._Speciaite;
			}
			set
			{
				if ((this._Speciaite != value))
				{
					this.OnSpeciaiteChanging(value);
					this.SendPropertyChanging();
					this._Speciaite = value;
					this.SendPropertyChanged("Speciaite");
					this.OnSpeciaiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Site Web]", Storage="_Site_Web", DbType="NVarChar(100)")]
		public string Site_Web
		{
			get
			{
				return this._Site_Web;
			}
			set
			{
				if ((this._Site_Web != value))
				{
					this.OnSite_WebChanging(value);
					this.SendPropertyChanging();
					this._Site_Web = value;
					this.SendPropertyChanged("Site_Web");
					this.OnSite_WebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomGerant", DbType="NVarChar(30)")]
		public string NomGerant
		{
			get
			{
				return this._NomGerant;
			}
			set
			{
				if ((this._NomGerant != value))
				{
					this.OnNomGerantChanging(value);
					this.SendPropertyChanging();
					this._NomGerant = value;
					this.SendPropertyChanged("NomGerant");
					this.OnNomGerantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrenomGerant", DbType="NVarChar(30)")]
		public string PrenomGerant
		{
			get
			{
				return this._PrenomGerant;
			}
			set
			{
				if ((this._PrenomGerant != value))
				{
					this.OnPrenomGerantChanging(value);
					this.SendPropertyChanging();
					this._PrenomGerant = value;
					this.SendPropertyChanged("PrenomGerant");
					this.OnPrenomGerantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="NVarChar(100)")]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(25)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(25)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailGerant", DbType="NVarChar(50)")]
		public string MailGerant
		{
			get
			{
				return this._MailGerant;
			}
			set
			{
				if ((this._MailGerant != value))
				{
					this.OnMailGerantChanging(value);
					this.SendPropertyChanging();
					this._MailGerant = value;
					this.SendPropertyChanged("MailGerant");
					this.OnMailGerantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroRC", DbType="NVarChar(100)")]
		public string NumeroRC
		{
			get
			{
				return this._NumeroRC;
			}
			set
			{
				if ((this._NumeroRC != value))
				{
					this.OnNumeroRCChanging(value);
					this.SendPropertyChanging();
					this._NumeroRC = value;
					this.SendPropertyChanged("NumeroRC");
					this.OnNumeroRCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFiscale", DbType="NVarChar(50)")]
		public string IdFiscale
		{
			get
			{
				return this._IdFiscale;
			}
			set
			{
				if ((this._IdFiscale != value))
				{
					this.OnIdFiscaleChanging(value);
					this.SendPropertyChanging();
					this._IdFiscale = value;
					this.SendPropertyChanged("IdFiscale");
					this.OnIdFiscaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wilaya", DbType="NVarChar(50)")]
		public string Wilaya
		{
			get
			{
				return this._Wilaya;
			}
			set
			{
				if ((this._Wilaya != value))
				{
					this.OnWilayaChanging(value);
					this.SendPropertyChanging();
					this._Wilaya = value;
					this.SendPropertyChanged("Wilaya");
					this.OnWilayaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cle
		{
			get
			{
				return this._Cle;
			}
			set
			{
				if ((this._Cle != value))
				{
					this.OnCleChanging(value);
					this.SendPropertyChanging();
					this._Cle = value;
					this.SendPropertyChanged("Cle");
					this.OnCleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Salaires")]
	public partial class Salaires : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<decimal> _Salaire;
		
		private System.Nullable<System.DateTime> _DateDajout;
		
		private System.Nullable<int> _Matricule;
		
		private EntityRef<Employe> _Employe;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSalaireChanging(System.Nullable<decimal> value);
    partial void OnSalaireChanged();
    partial void OnDateDajoutChanging(System.Nullable<System.DateTime> value);
    partial void OnDateDajoutChanged();
    partial void OnMatriculeChanging(System.Nullable<int> value);
    partial void OnMatriculeChanged();
    #endregion
		
		public Salaires()
		{
			this._Employe = default(EntityRef<Employe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salaire", DbType="Money")]
		public System.Nullable<decimal> Salaire
		{
			get
			{
				return this._Salaire;
			}
			set
			{
				if ((this._Salaire != value))
				{
					this.OnSalaireChanging(value);
					this.SendPropertyChanging();
					this._Salaire = value;
					this.SendPropertyChanged("Salaire");
					this.OnSalaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDajout", DbType="Date")]
		public System.Nullable<System.DateTime> DateDajout
		{
			get
			{
				return this._DateDajout;
			}
			set
			{
				if ((this._DateDajout != value))
				{
					this.OnDateDajoutChanging(value);
					this.SendPropertyChanging();
					this._DateDajout = value;
					this.SendPropertyChanged("DateDajout");
					this.OnDateDajoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricule", DbType="Int")]
		public System.Nullable<int> Matricule
		{
			get
			{
				return this._Matricule;
			}
			set
			{
				if ((this._Matricule != value))
				{
					if (this._Employe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatriculeChanging(value);
					this.SendPropertyChanging();
					this._Matricule = value;
					this.SendPropertyChanged("Matricule");
					this.OnMatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employe_Salaires", Storage="_Employe", ThisKey="Matricule", OtherKey="Matricule", IsForeignKey=true)]
		public Employe Employe
		{
			get
			{
				return this._Employe.Entity;
			}
			set
			{
				Employe previousValue = this._Employe.Entity;
				if (((previousValue != value) 
							|| (this._Employe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employe.Entity = null;
						previousValue.Salaires.Remove(this);
					}
					this._Employe.Entity = value;
					if ((value != null))
					{
						value.Salaires.Add(this);
						this._Matricule = value.Matricule;
					}
					else
					{
						this._Matricule = default(Nullable<int>);
					}
					this.SendPropertyChanged("Employe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Identifiant;
		
		private string _MDP;
		
		private string _Qualite;
		
		private string _ThemeApp;
		
		private string _QuestSec1;
		
		private string _Reponse1;
		
		private string _QuestSec2;
		
		private string _Reponse2;
		
		private int _ID;
		
		private System.Data.Linq.Binary _Photo_Profil;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentifiantChanging(string value);
    partial void OnIdentifiantChanged();
    partial void OnMDPChanging(string value);
    partial void OnMDPChanged();
    partial void OnQualiteChanging(string value);
    partial void OnQualiteChanged();
    partial void OnThemeAppChanging(string value);
    partial void OnThemeAppChanged();
    partial void OnQuestSec1Changing(string value);
    partial void OnQuestSec1Changed();
    partial void OnReponse1Changing(string value);
    partial void OnReponse1Changed();
    partial void OnQuestSec2Changing(string value);
    partial void OnQuestSec2Changed();
    partial void OnReponse2Changing(string value);
    partial void OnReponse2Changed();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPhoto_ProfilChanging(System.Data.Linq.Binary value);
    partial void OnPhoto_ProfilChanged();
    #endregion
		
		public Users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identifiant", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Identifiant
		{
			get
			{
				return this._Identifiant;
			}
			set
			{
				if ((this._Identifiant != value))
				{
					this.OnIdentifiantChanging(value);
					this.SendPropertyChanging();
					this._Identifiant = value;
					this.SendPropertyChanged("Identifiant");
					this.OnIdentifiantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDP", DbType="NVarChar(25)")]
		public string MDP
		{
			get
			{
				return this._MDP;
			}
			set
			{
				if ((this._MDP != value))
				{
					this.OnMDPChanging(value);
					this.SendPropertyChanging();
					this._MDP = value;
					this.SendPropertyChanged("MDP");
					this.OnMDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qualite", DbType="NVarChar(20)")]
		public string Qualite
		{
			get
			{
				return this._Qualite;
			}
			set
			{
				if ((this._Qualite != value))
				{
					this.OnQualiteChanging(value);
					this.SendPropertyChanging();
					this._Qualite = value;
					this.SendPropertyChanged("Qualite");
					this.OnQualiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThemeApp", DbType="NVarChar(50)")]
		public string ThemeApp
		{
			get
			{
				return this._ThemeApp;
			}
			set
			{
				if ((this._ThemeApp != value))
				{
					this.OnThemeAppChanging(value);
					this.SendPropertyChanging();
					this._ThemeApp = value;
					this.SendPropertyChanged("ThemeApp");
					this.OnThemeAppChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestSec1", DbType="NVarChar(MAX)")]
		public string QuestSec1
		{
			get
			{
				return this._QuestSec1;
			}
			set
			{
				if ((this._QuestSec1 != value))
				{
					this.OnQuestSec1Changing(value);
					this.SendPropertyChanging();
					this._QuestSec1 = value;
					this.SendPropertyChanged("QuestSec1");
					this.OnQuestSec1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reponse1", DbType="NVarChar(50)")]
		public string Reponse1
		{
			get
			{
				return this._Reponse1;
			}
			set
			{
				if ((this._Reponse1 != value))
				{
					this.OnReponse1Changing(value);
					this.SendPropertyChanging();
					this._Reponse1 = value;
					this.SendPropertyChanged("Reponse1");
					this.OnReponse1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestSec2", DbType="NVarChar(MAX)")]
		public string QuestSec2
		{
			get
			{
				return this._QuestSec2;
			}
			set
			{
				if ((this._QuestSec2 != value))
				{
					this.OnQuestSec2Changing(value);
					this.SendPropertyChanging();
					this._QuestSec2 = value;
					this.SendPropertyChanged("QuestSec2");
					this.OnQuestSec2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reponse2", DbType="NVarChar(50)")]
		public string Reponse2
		{
			get
			{
				return this._Reponse2;
			}
			set
			{
				if ((this._Reponse2 != value))
				{
					this.OnReponse2Changing(value);
					this.SendPropertyChanging();
					this._Reponse2 = value;
					this.SendPropertyChanged("Reponse2");
					this.OnReponse2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo_Profil", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo_Profil
		{
			get
			{
				return this._Photo_Profil;
			}
			set
			{
				if ((this._Photo_Profil != value))
				{
					this.OnPhoto_ProfilChanging(value);
					this.SendPropertyChanging();
					this._Photo_Profil = value;
					this.SendPropertyChanged("Photo_Profil");
					this.OnPhoto_ProfilChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
